# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/mt6785-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter RMX2001,$(TARGET_DEVICE)),)

endif
