# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RMX2001/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/RMX2001

PRODUCT_COPY_FILES += \
    vendor/realme/RMX2001/proprietary/product/vendor_overlay/29/lib/libdpframework.so:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/lib/libdpframework.so \
    vendor/realme/RMX2001/proprietary/product/vendor_overlay/29/lib/libvpud_vcodec.so:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/lib/libvpud_vcodec.so \
    vendor/realme/RMX2001/proprietary/product/vendor_overlay/29/lib64/libcameracustom.so:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/lib64/libcameracustom.so \
    vendor/realme/RMX2001/proprietary/product/vendor_overlay/29/lib64/libdpframework.so:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/lib64/libdpframework.so
