# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/mt6785-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/mt6785-common

PRODUCT_COPY_FILES += \
    vendor/realme/mt6785-common/proprietary/bin/kpoc_charger:$(TARGET_COPY_OUT_SYSTEM)/bin/kpoc_charger \
    vendor/realme/mt6785-common/proprietary/product/etc/apns-conf.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/apns-conf.xml \
    vendor/realme/mt6785-common/proprietary/etc/init/kpoc_charger.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/kpoc_charger.rc \
    vendor/realme/mt6785-common/proprietary/lib/libshowlogo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libshowlogo.so \
    vendor/realme/mt6785-common/proprietary/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptXHD_encoder.so \
    vendor/realme/mt6785-common/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so

PRODUCT_PACKAGES += \
    HotwordEnrollmentOKGoogleCORTEXM4
